@echo Generating makefiles...
qmake WeatherForecast.pro -r -spec win32-msvc2010 CONFIG+=debug_and_release %CONFIG%
@echo Generating solutions...
qmake WeatherForecast.pro -r -spec win32-msvc2010 -tp vc %CONFIG%
